### ISSUE TITLE
dependent install error

### ISSUE THREAD

**Issue by juicechu** [DanMcInerney/xsscrapy#10]
sudo pip install -r requirements.txt 
but error message

```
writing manifest file 'Twisted.egg-info/SOURCES.txt'

warning: manifest_maker: standard file '-c' not found



reading manifest file 'Twisted.egg-info/SOURCES.txt'

writing manifest file 'Twisted.egg-info/SOURCES.txt'

copying twisted/runner/portmap.c -> build/lib.linux-x86_64-2.7/twisted/runner

creating build/lib.linux-x86_64-2.7/twisted/internet/iocpreactor/iocpsupport

copying twisted/internet/iocpreactor/iocpsupport/iocpsupport.c -> build/lib.linux-x86_64-2.7/twisted/internet/iocpreactor/iocpsupport

copying twisted/internet/iocpreactor/iocpsupport/winsock_pointers.c -> build/lib.linux-x86_64-2.7/twisted/internet/iocpreactor/iocpsupport

copying twisted/python/sendmsg.c -> build/lib.linux-x86_64-2.7/twisted/python

copying twisted/test/raiser.c -> build/lib.linux-x86_64-2.7/twisted/test

running build_ext

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c conftest.c -o conftest.o

building 'twisted.runner.portmap' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/twisted

creating build/temp.linux-x86_64-2.7/twisted/runner

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c twisted/runner/portmap.c -o build/temp.linux-x86_64-2.7/twisted/runner/portmap.o

twisted/runner/portmap.c:10:20: fatal error: Python.h: No such file or directory

 #include <Python.h>

                    ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools;__file__='/tmp/pip_build_root/Twisted/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1LsoSA-record/install-record.txt --single-version-externally-managed failed with error code 1 in /tmp/pip_build_root/Twisted
Storing complete log in /home/geekzhu/.pip/pip.log

```

**Comment by manishthakur101** [comment]
i had type this command line but this is giving an error

pip3 install -r requirements.txt 
Collecting Scrapy==1.1.0rc3
  Using cached Scrapy-1.1.0rc3-py2.py3-none-any.whl (292 kB)
Collecting pybloom==1.1
  Using cached pybloom-1.1.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kl40ngra/pybloom/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kl40ngra/pybloom/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-kl40ngra/pybloom/pip-egg-info
         cwd: /tmp/pip-install-kl40ngra/pybloom/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kl40ngra/pybloom/setup.py", line 2, in <module>
        from ez_setup import use_setuptools
      File "/tmp/pip-install-kl40ngra/pybloom/ez_setup.py", line 98
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


can anyone help me out @DanMcInerney

**Comment by decidedlygray** [comment]
Hello @manishthakur101 - I would recommend starting a new ticket, this one is closed

I believe your problem is that you are using pip3. From what I remember this project is Python2, not Python3, so you would want to use:
**pip** install -r requirements.txt

**Comment by addycracker** [comment]
@manishthakur101 same here

**Comment by addycracker** [comment]
@decidedlygray not working

**Comment by decidedlygray** [comment]
@addycracker your message isn’t super helpful. In what way is that not working? What OS are you using? Do you have a stack trace, recreation steps or screenshots you can share? Etc.

also same advice as before: start a new ticket that isn’t marked as closed
