### ISSUE TITLE
fatal problem after up to date kali install new python install and xssscrapy from scartch 

### ISSUE THREAD

**Issue by lacroutelacroute** [DanMcInerney/xsscrapy#35]
hey

i encouter fatal error
after install up to date kali new python install and xssscrapy from scratch

fakessh@fakessh:/opt/xssscrapy/xsscrapy$ sudo pip install --upgrade  -r requirements.txt
[sudo] Mot de passe de fakessh : 
Requirement already up-to-date: Scrapy==1.1.0rc3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: pybloom==1.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: requests in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: beautifulsoup in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: Twisted in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: w3lib in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already up-to-date: lxml in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already up-to-date: six in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Requirement already up-to-date: cssselect in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already up-to-date: pyopenssl in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
Requirement already up-to-date: cryptography in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already up-to-date: queuelib in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Requirement already up-to-date: service-identity in /usr/lib/python2.7/dist-packages (from Scrapy==1.1.0rc3->-r requirements.txt (line 2))
Requirement already up-to-date: parsel>=0.9.3 in /usr/local/lib/python2.7/dist-packages (from Scrapy==1.1.0rc3->-r requirements.txt (line 2))
Requirement already up-to-date: PyDispatcher>=2.0.5 in /usr/local/lib/python2.7/dist-packages (from Scrapy==1.1.0rc3->-r requirements.txt (line 2))
Requirement already up-to-date: bitarray>=0.3.4 in /usr/local/lib/python2.7/dist-packages (from pybloom==1.1->-r requirements.txt (line 3))
Requirement already up-to-date: Automat>=0.3.0 in /usr/local/lib/python2.7/dist-packages (from Twisted->-r requirements.txt (line 6))
Requirement already up-to-date: constantly>=15.1 in /usr/lib/python2.7/dist-packages (from Twisted->-r requirements.txt (line 6))
Requirement already up-to-date: incremental>=16.10.1 in /usr/lib/python2.7/dist-packages (from Twisted->-r requirements.txt (line 6))
Requirement already up-to-date: zope.interface>=3.6.0 in /usr/local/lib/python2.7/dist-packages (from Twisted->-r requirements.txt (line 6))
Requirement already up-to-date: setuptools>=11.3 in /usr/local/lib/python2.7/dist-packages (from cryptography->-r requirements.txt (line 12))
Requirement already up-to-date: ipaddress in /usr/local/lib/python2.7/dist-packages (from cryptography->-r requirements.txt (line 12))
Requirement already up-to-date: idna>=2.1 in /usr/local/lib/python2.7/dist-packages (from cryptography->-r requirements.txt (line 12))
Requirement already up-to-date: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography->-r requirements.txt (line 12))
Requirement already up-to-date: enum34 in /usr/lib/python2.7/dist-packages (from cryptography->-r requirements.txt (line 12))
Requirement already up-to-date: cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography->-r requirements.txt (line 12))
Requirement already up-to-date: packaging in /usr/local/lib/python2.7/dist-packages (from cryptography->-r requirements.txt (line 12))
Requirement already up-to-date: attrs in /usr/lib/python2.7/dist-packages (from Automat>=0.3.0->Twisted->-r requirements.txt (line 6))
Requirement already up-to-date: appdirs>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from setuptools>=11.3->cryptography->-r requirements.txt (line 12))
Requirement already up-to-date: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography->-r requirements.txt (line 12))
Requirement already up-to-date: pyparsing in /usr/local/lib/python2.7/dist-packages (from packaging->cryptography->-r requirements.txt (line 12))
fakessh@fakessh:/opt/xssscrapy/xsscrapy$ sudo python ./xsscrapy.py -u  http://www.airarabia.com/en    -r 120
2017-03-10 20:13:13 [scrapy] INFO: Scrapy 1.1.0rc3 started (bot: xsscrapy)
2017-03-10 20:13:13 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'xsscrapy.spiders', 'DUPEFILTER_CLASS': 'xsscrapy.bloomfilters.BloomURLDupeFilter', 'SPIDER_MODULES': ['xsscrapy.spiders'], 'CONCURRENT_REQUESTS': '30', 'BOT_NAME': 'xsscrapy', 'DOWNLOAD_DELAY': '0.5'}
2017-03-10 20:13:13 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2017-03-10 20:13:13 [scrapy] INFO: Enabled downloader middlewares:
['xsscrapy.middlewares.InjectedDupeFilter',
 'xsscrapy.middlewares.RandomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.chunked.ChunkedTransferMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2017-03-10 20:13:13 [scrapy] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2017-03-10 20:13:13 [scrapy] INFO: Enabled item pipelines:
['xsscrapy.pipelines.XSSCharFinder']
2017-03-10 20:13:13 [scrapy] INFO: Spider opened
2017-03-10 20:13:13 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2017-03-10 20:13:13 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
2017-03-10 20:13:13 [scrapy] ERROR: Error downloading <GET http://www.airarabia.com/en>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 45, in mustbe_deferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/downloader/handlers/__init__.py", line 65, in download_request
    return handler.download_request(request, spider)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/downloader/handlers/http11.py", line 60, in download_request
    return agent.download_request(request)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/downloader/handlers/http11.py", line 264, in download_request
    method, to_bytes(url, encoding='ascii'), headers, bodyproducer)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/client.py", line 1631, in request
    parsedURI.originForm)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/client.py", line 1408, in _requestWithEndpoint
    d = self._pool.getConnection(key, endpoint)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/client.py", line 1294, in getConnection
    return self._newConnection(key, endpoint)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/client.py", line 1306, in _newConnection
    return endpoint.connect(factory)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/endpoints.py", line 788, in connect
    EndpointReceiver, self._hostText, portNumber=self._port
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_resolver.py", line 174, in resolveHostName
    onAddress = self._simpleResolver.getHostByName(hostName)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/resolver.py", line 21, in getHostByName
    d = super(CachingThreadedResolver, self).getHostByName(name, timeout)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 276, in getHostByName
    timeoutDelay = sum(timeout)
TypeError: 'float' object is not iterable
2017-03-10 20:13:14 [scrapy] INFO: Closing spider (finished)
2017-03-10 20:13:14 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 1,
 'downloader/exception_type_count/exceptions.TypeError': 1,
 'downloader/request_bytes': 304,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2017, 3, 10, 19, 13, 14, 138599),
 'log_count/DEBUG': 1,
 'log_count/ERROR': 1,
 'log_count/INFO': 7,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2017, 3, 10, 19, 13, 13, 720985)}
2017-03-10 20:13:14 [scrapy] INFO: Spider closed (finished)
fakessh@fakessh:/opt/xssscrapy/xsscrapy$ 
$ sudo python ./xsscrapy.py -h
usage: xsscrapy.py [-h] [-u URL] [-l LOGIN] [-p PASSWORD] [-c CONNECTIONS]
                   [-r RATELIMIT] [--basic] [-k COOKIE]

optional arguments:
  -h, --help            show this help message and exit
  -u URL, --url URL     URL to scan; -u http://example.com
  -l LOGIN, --login LOGIN
                        Login name; -l danmcinerney
  -p PASSWORD, --password PASSWORD
                        Password; -p pa$$w0rd
  -c CONNECTIONS, --connections CONNECTIONS
                        Set the max number of simultaneous connections
                        allowed, default=30
  -r RATELIMIT, --ratelimit RATELIMIT
                        Rate in requests per minute, default=0
  --basic               Use HTTP Basic Auth to login
  -k COOKIE, --cookie COOKIE
                        Cookie key; --cookie
                        SessionID=afgh3193e9103bca9318031bcdf
fakessh@fakessh:/opt/xssscrapy/xsscrapy$

**Comment by lacroutelacroute** [comment]
work file with 
sudo pip install twisted==16.6.0

**Comment by DanMcInerney** [comment]
Fixed requirements.txt
